name: flat_buffers
version: 1.12.0+1
description:
  Library for reading and writing FlatBuffers. Use the flatc compiler to
  generate Dart classes from a FlatBuffer schema, and this library read and write the binary format.
homepage: https://github.com/google/flatbuffers
documentation: https://google.github.io/flatbuffers/index.html
dev_dependencies:
  test: ^1.3.0
  test_reflective_loader: ^0.1.4
  path: ^1.5.1
environment:
  sdk: '>=2.0.0 <3.0.0'
  
