name: flatc
base: core18
version: git
summary: FlatBuffers compiler
description: |
  FlatBuffers compiler

grade: devel
confinement: strict

parts:
  flatc:
    plugin: cmake
    source: .
    configflags:
      - -GUnix Makefiles
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - g++

apps:
  flatc:
    command: flatc
    plugs:
      - home
