name: Notify users based on issue labels

on:
  issues:
      types: [labeled]
  pull_request:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: kongo555/issue-label-notification-action@master
          with:
             recipients: |
                  lua=@dbaileychess
                  c++=@aardappel